name: CI

on: push

jobs:
  analysis:
    strategy:
      matrix:
        elixir: [1.9]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master

      - uses: actions/docker/cli@master

      - name: Pull elixir:${{ matrix.elixir }}-alpine
        run: docker pull elixir:${{ matrix.elixir }}-alpine

      - name: Run `mix dialyzer`
        run: |
          cmd='
            mix local.hex --force;
            mix local.rebar --force;
            mix deps.get;
            mix dialyzer;
          '
          docker run \
            --mount type=bind,src=`pwd`,target=/usr/src/shopify-graphql \
            -w /usr/src/shopify-graphql elixir:${{ matrix.elixir }}-alpine \
            /bin/ash -c "$cmd"

  test:
    strategy:
      matrix:
        elixir: [1.9]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master

      - uses: actions/docker/cli@master

      - name: Pull elixir:${{ matrix.elixir }}-alpine
        run: docker pull elixir:${{ matrix.elixir }}-alpine

      - name: Run `mix test`
        run: |
          cmd='
            mix local.hex --force;
            mix local.rebar --force;
            mix deps.get;
            mix test;
          '
          docker run \
            --mount type=bind,src=`pwd`,target=/usr/src/shopify-graphql \
            -w /usr/src/shopify-graphql elixir:${{ matrix.elixir }}-alpine \
            /bin/ash -c "$cmd"
